- name: configure ntp
  tags: [server, ntp, time]
  template: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: install ntp service
  tags: [server, ntp, time]
  copy: src=ntp.service dest=/etc/systemd/system/ntp.service
  notify:
    - reload systemd
    - restart ntp

- name: enable and start ntp
  tags: [server, ntp, time]
  service: name=ntp state=started enabled=yes
