dependencies:
  - { role: accounts/add_group, group: { name: nsd, system: yes } }
  - { role: accounts/add_user, user: { name: nsd, group: nsd, home: /srv/dns, system: yes } }
  - { role: packages/install, package: nsd }
