- name: transfer zone {{ zone }}
  tags: [zone, dns]
  copy: src={{ zonefile }} dest=/srv/dns/{{ zonefile|basename }}
  notify: reload nsd

- name: configure zone {{ zone }}
  tags: [zone, dns]
  template: src=zone.conf dest=/etc/nsd/nsd.conf.d/{{ zone }}.conf
  notify: reload nsd

- name: include zone {{ zone }}
  tags: [zone, dns]
  lineinfile: >
    dest=/etc/nsd/nsd.conf.d.conf
    line="include: /etc/nsd/nsd.conf.d/{{ zone }}.conf"
    insertafter=EOF
  notify: reload nsd
