dependencies:
  - role: file/directory
    path: /usr/local/lib/collectd

  - role: packages/apt
    args:
      pkg: collectd
  - role: packages/apt
    args:
      pkg: collectd-utils

  - role: packages/apt
    args:
      pkg: sane-utils
      state: absent
      purge: yes
  - role: packages/apt
    args:
      pkg: libsane
      state: absent
      purge: yes
