- name: harden | disable password authentication
  tags: [harden, ssh, security]
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp='^#?PasswordAuthentication'
    line='PasswordAuthentication no'
    state=present
  notify: restart ssh
