dependencies:
  - role: packages/apt
    args:
      pkg: openjdk-7-jre

  - role: packages/apt/add_key
    args:
      id: D88E42B4
      url: 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch'
  - role: packages/apt/add_repo
    args:
      repo: 'deb http://packages.elasticsearch.org/logstash/1.4/debian stable main'

  - role: packages/apt
    args:
      pkg: logstash
  - role: packages/apt
    args:
      pkg: logstash-contrib
