dependencies:
  - role: packages/apt
    args:
      pkg: bsd-mailx
  - role: packages/apt
    args:
      pkg: postfix

  - role: packages/apt
    args:
      pkg: exim4
      state: absent
      purge: yes
  - role: packages/apt
    args:
      pkg: exim4-base
      state: absent
      purge: yes
  - role: packages/apt
    args:
      pkg: exim4-config
      state: absent
      purge: yes
  - role: packages/apt
    args:
      pkg: exim4-daemon-light
      state: absent
      purge: yes
