- name: configure ferm
  tags: [ferm, network]
  template: src=ferm.conf dest=/etc/ferm/ferm.conf
  notify: reload ferm

- name: install ferm service
  tags: [ferm, network]
  copy: src=ferm.service dest=/etc/systemd/system/ferm.service
  notify:
    - reload systemd
    - reload ferm

- name: enable and start ferm
  tags: [ferm, network]
  service: name=ferm state=started enabled=yes
