- name: bind to all interfaces
  tags: [redis, database]
  lineinfile: >
    dest=/etc/redis/redis.conf
    regexp='^bind '
    line='bind 0.0.0.0'
    state=present
  notify: restart redis

- name: enable aof
  tags: [redis, database]
  lineinfile: >
    dest=/etc/redis/redis.conf
    regexp='^appendonly '
    line='appendonly yes'
    state=present
  notify: restart redis
