- name: configure redis
  tags: [redis, database]
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: restart redis

- name: enable and start redis
  tags: [redis, database]
  service: name=redis-server state=started enabled=yes
