- name: get kernel version
  tags: [pvgrub, system]
  shell: dpkg -s linux-image-amd64|awk '/Depends/{sub(/linux-image-/,""); print $2}'
  register: kernel_version
  changed_when: false

- name: configure (pv)grub
  tags: [pvgrub, system]
  template: src=menu.lst dest=/boot/grub/menu.lst
