- name: check if systemd is running
  tags: [systemd, system]
  command: test -d /run/systemd/system
  ignore_errors: yes
  register: systemd
  changed_when: false

- name: reboot into systemd
  tags: [systemd, system]
  command: shutdown -r now "rebooting into systemd"
  async: 0
  poll: 0
  register: reboot
  when: systemd|failed

- name: wait for host to come back
  tags: [systemd, system]
  local_action: wait_for host={{ inventory_hostname }} port={{ ansible_ssh_port|default(22) }} search_regex=OpenSSH delay=10
  sudo: false
  when: reboot|changed

- name: disable rc.local
  tags: [systemd, system]
  file: path=/etc/rc.local mode=644
