- name: configure sysctls
  tags: [tuning, system]
  with_dict:
    # Disable SysRQ.
    kernel.sysrq: 0
    # Lock down dmesg.
    kernel.dmesg_restrict: 1

    # Use swap please.
    vm.swappiness: 80
    # And overcommit memory.
    vm.overcommit_memory: 1

    # Enable forwarding.
    net.ipv4.conf.all.forwarding: 1
    net.ipv6.conf.all.forwarding: 1
    # Don't accept router advertisements.
    net.ipv6.conf.all.accept_ra: 0

    # Prevent SYN floods with cookies.
    net.ipv4.tcp_syncookies: 1
    # Drop RSTs for sockets in time-wait.
    net.ipv4.tcp_rfc1337: 1

    # Prevent wrapping of sequence numbers.
    net.ipv4.tcp_timestamps: 1

    # Enlarge the conntrack tables, lower timeouts.
    net.netfilter.nf_conntrack_max: 262272
  sysctl: name='{{ item.key }}' value='{{ item.value }}'
