- name: configure sysctls
  tags: [tuning, system]
  with_dict:
    # Disable SysRQ.
    kernel.sysrq: 0
    # Lock down dmesg.
    kernel.dmesg_restrict: 1

    # Use swap please.
    vm.swappiness: 80

    # Enable forwarding.
    net.ipv4.conf.all.forwarding: 1
    net.ipv6.conf.all.forwarding: 1
    # Don't accept router advertisements.
    net.ipv6.conf.all.accept_ra: 0

    # Prevent SYN floods with cookies.
    net.ipv4.tcp_syncookies: 1
    # Drop RSTs for sockets in time-wait.
    net.ipv4.tcp_rfc1337: 1

    # Prevent wrapping of sequence numbers.
    net.ipv4.tcp_timestamps: 1

    # Enlarge the conntrack tables, lower timeouts.
    net.netfilter.nf_conntrack_max: 262272
    net.netfilter.nf_conntrack_generic_timeout: 600
    net.netfilter.nf_conntrack_frag6_timeout: 60
    net.netfilter.nf_conntrack_icmp_timeout: 30
    net.netfilter.nf_conntrack_icmpv6_timeout: 30
    net.netfilter.nf_conntrack_tcp_timeout_close: 10
    net.netfilter.nf_conntrack_tcp_timeout_close_wait: 60
    net.netfilter.nf_conntrack_tcp_timeout_established: 21600
    net.netfilter.nf_conntrack_tcp_timeout_fin_wait: 120
    net.netfilter.nf_conntrack_tcp_timeout_last_ack: 30
    net.netfilter.nf_conntrack_tcp_timeout_max_retrans: 300
    net.netfilter.nf_conntrack_tcp_timeout_syn_recv: 60
    net.netfilter.nf_conntrack_tcp_timeout_syn_sent: 120
    net.netfilter.nf_conntrack_tcp_timeout_time_wait: 120
    net.netfilter.nf_conntrack_tcp_timeout_unacknowledged: 300
    net.netfilter.nf_conntrack_udp_timeout: 30
    net.netfilter.nf_conntrack_udp_timeout_stream: 180
    net.netfilter.nf_conntrack_events_retry_timeout: 15
  sysctl: name='{{ item.key }}' value='{{ item.value }}'
