dependencies:
  - role: tools/git
  - role: tools/curl
  - role: tools/ack-grep
  - role: tools/apt-file
  - role: tools/htop
  - role: tools/iftop
  - role: tools/iotop
  - role: tools/tcpdump
  - role: tools/mosh
