- name: configure influxdb
  tags: [influxdb, database]
  template: src=config.toml dest=/opt/influxdb/shared/config.toml
  notify: restart influxdb

- name: install influxdb service
  tags: [influxdb, database]
  copy: src=influxdb.service dest=/etc/systemd/system/influxdb.service
  notify:
    - reload systemd
    - restart influxdb

- name: enable and start influxdb
  tags: [influxdb, database]
  service: name=influxdb state=started enabled=yes
