dependencies:
  - role: packages/apt/add_key
    args:
      id: 74D9DBB5
      url: 'https://prosody.im/files/prosody-debian-packages.key'
  - role: packages/apt/add_repo
    args:
      repo: 'deb http://packages.prosody.im/debian unstable main'

  - role: packages/apt
    args:
      pkg: prosody
  - role: packages/apt
    args:
      pkg: lua-zlib
