- name: load module {{ module }}
  tags: [tuning, system]
  modprobe: name={{ module }} state=present

- name: configure module {{ module }}
  tags: [tuning, system]
  copy: content='{{ module }}\n' dest=/etc/modules-load.d/{{ module }}.conf
  notify: reload kernel modules
