- name: reload systemd
  command: systemctl daemon-reload

- name: reload domains
  command: postmap /etc/postfix/domains

- name: reload passwd
  command: postmap /etc/postfix/passwd

- name: restart postfix
  service: name=postfix state=restarted
