- name: reload systemd
  command: systemctl daemon-reload

- name: reload tmpfiles
  command: systemd-tmpfiles --remove --create

- name: reload prosody
  service: name=prosody state=reloaded

- name: restart prosody
  service: name=prosody state=restarted
