- name: clone gitolite
  tags: [gitolite, storage]
  sudo_user: git
  git: repo=git://github.com/sitaramc/gitolite dest=/srv/git/gitolite accept_hostkey=yes

- name: setup gitolite
  tags: [gitolite, storage]
  sudo_user: git
  command: /srv/git/gitolite/src/gitolite setup -a dummy creates=/srv/git/projects.list

- name: purge config repository
  tags: [gitolite, storage]
  sudo_user: git
  file: path=/srv/git/repositories/gitolite-admin.git state=absent

- name: configure gitolite
  tags: [gitolite, storage]
  sudo_user: git
  template: src=gitolite.rc dest=/srv/git/.gitolite.rc

- name: configure gitolite repos
  tags: [gitolite, storage]
  sudo_user: git
  template: src=gitolite.conf dest=/srv/git/.gitolite/conf/gitolite.conf
  notify:
    - recompile gitolite config
    - setup gitolite

- name: create keydir
  tags: [gitolite, storage]
  sudo_user: git
  file: path=/srv/git/.gitolite/keydir state=directory

- name: create users
  tags: [gitolite, storage]
  sudo_user: git
  with_dict: users
  copy: content='{{ item.value }}' dest=/srv/git/.gitolite/keydir/{{ item.key }}.pub
  notify: reload gitolite keys
