- name: nginx | install nginx
  tags: [packages]
  apt: pkg=nginx-extras state=latest

- name: nginx | install spawn-fcgi
  tags: [packages]
  apt: pkg=spawn-fcgi state=latest

- name: nginx | configure nginx
  tags: [config]
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: nginx | restart

- name: nginx | configure vhosts
  tags: [config]
  template: src=vhost.conf dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: webserver_vhosts
  notify: nginx | reload

- name: nginx | enable and start nginx
  tags: [services]
  service: name=nginx state=started enabled=yes
