#!/bin/sh

### BEGIN INIT INFO
# Provides:          nbnc
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: null (transparent) bnc
# Description:       null (transparent) bnc
### END INIT INFO

. /lib/lsb/init-functions

start() {
{% for listen, net in nbncs.iteritems() if net.4 is defined %}
start-stop-daemon -S -c nbnc \
  -x /srv/nbnc/bin/nbnc \
  -p /var/run/nbnc.{{ listen }}.pid -m  \
  -b \
  -- \
  -L {{ listen }} \
  -r {{ net.ip }} -R {{ net.port }} \
  -o {{ nbnc_ip.4 }} -4 \
  -p {{ nbnc_pass }}
{% endfor %}
{% for listen, net in nbncs.iteritems() if net.6 is defined %}
start-stop-daemon -S -c nbnc \
  -x /srv/nbnc/bin/nbnc \
  -p /var/run/nbnc.{{ listen }}.pid -m  \
  -b \
  -- \
  -L {{ listen }} \
  -r {{ net.ip }} -R {{ net.port }} \
  -o [{{ nbnc_ip.6 }}] -6 \
  -p {{ nbnc_pass }}
{% endfor %}
}

stop() {
{% for listen in nbncs %}
start-stop-daemon -K -c nbnc \
  -x /srv/nbnc/bin/nbnc \
  -p /var/run/nbnc.{{ listen }}.pid
{% endfor %}
}

status() {
  if ps ax | grep -v grep | grep '/srv/nbnc/bin/nbnc' >/dev/null 2>&1; then
    log_success_msg 'nbnc running'
  else
    log_failure_msg 'nbnc not running'; exit 3
  fi
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; sleep 3; start ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}" ;;
esac
