#!/usr/bin/env bash

ZONEDIR=/srv/dns
KEYDIR=/srv/dns/keys

zone=$1

unsigned_zone=/$ZONEDIR/${zone}.db
signed_zone=/$ZONEDIR/${zone}.s.db

ldns-signzone -n -f ${signed_zone} ${unsigned_zone} $(ls $KEYDIR/K${zone}.+*+*.private | sed 's/\.private//')
