- name: knot | install knot (apt)
  apt: pkg=knot state=latest
  when: ansible_pkg_mgr == 'apt'

- name: knot | configure knot
  template: src=knot.conf dest=/etc/knot/knot.conf owner=knot
  notify: restart knotd

- name: knot | configure zones
  with_dict: zones
  template: src=zone.db dest=/var/lib/knot/{{ item.key }}.db owner=knot
  notify: reload knotd

- name: knot | enable and start knot
  service: name=knot state=started enabled=yes
