- name: nsd | install nsd (apt)
  tags: [nsd, server, dns]
  with_items:
    - nsd
    - ldnsutils
  apt: pkg={{ item }} state=latest
  when: ansible_pkg_mgr == 'apt'

- name: nsd | configure nsd
  tags: [nsd, server, dns]
  template: src=nsd.conf dest=/etc/nsd/nsd.conf validate='nsd-checkconf %s'
  notify: restart nsd

- name: nsd | enable and start nsd
  tags: [nsd, server, dns]
  service: name=nsd state=started enabled=yes
