- name: nsd | install nsd (apt)
  apt: pkg=nsd state=latest
  when: ansible_pkg_mgr == 'apt'

- name: nsd | install ldns (apt)
  apt: pkg=ldnsutils state=latest
  when: ansible_pkg_mgr == 'apt'

- name: nsd | configure nsd
  template: src=nsd.conf dest=/etc/nsd/nsd.conf owner=nsd validate='nsd-checkconf %s'
  notify: restart nsd

- name: nsd | transfer keys
  copy: src=files/dns/keys/ dest=/srv/dns/keys/ owner=knot

- name: nsd | transfer zones
  with_dict: zones
  template: src=zone.db dest=/srv/dns/{{ item.key }}.db owner=nsd
  notify: reload nsd
  register: zonetransfer

- name: nsd | sign zones
  with_dict: zones
  when: zonetransfer.changed and item.value.dnssec
  script: signzone {{ item.key }}

- name: nsd | enable and start nsd
  service: name=nsd state=started enabled=yes
