- name: nsd | configure nsd.conf.d
  tags: [nsd, server, dns]
  file: path=/etc/nsd/nsd.conf.d.conf state=file

- name: nsd | configure nsd
  tags: [nsd, server, dns]
  template: src=nsd/nsd.conf dest=/etc/nsd/nsd.conf validate='nsd-checkconf %s'
  notify: restart nsd

- name: nsd | configure slaves
  tags: [nsd, server, dns]
  copy: src=nsd/slaves.conf dest=/etc/nsd/slaves.conf
  notify: restart nsd

- name: nsd | enable and start nsd
  tags: [nsd, server, dns]
  service: name=nsd state=started enabled=yes
