- name: ufw | install ufw
  tags: [packages]
  apt: pkg=ufw state=latest

- name: ufw | enable ipv6
  tags: [config]
  lineinfile: >
    dest=/etc/default/ufw
    state=present
    regexp='^IPV6'
    line='IPV6=yes'
  notify: ufw | reload

- name: ufw | configure rules
  tags: [config]
  ufw: >
    {% if item.value.port is defined %}port={{ item.value.port }}{% endif %}
    {% if item.value.proto is defined %}proto={{ item.value.proto }}{% endif %}
    {% if item.value.src is defined %}src={{ item.value.src }}{% endif %}
    {% if item.value.dest is defined %}dest={{ item.value.dest }}{% endif %}
    {% if item.value.direction is defined %}direction={{ item.value.direction }}{% endif %}
    {% if item.value.if is defined %}if={{ item.value.if }}{% endif %}
    {% if item.value.log is defined %}log={{ item.value.log }}{% endif %}
    {% if item.value.insert is defined %}insert={{ item.value.insert }}{% endif %}
    {% if item.value.delete is defined %}delete={{ item.value.delete }}{% endif %}
    rule={{ item.value.rule }}
  with_dict: firewall_rules
  notify: ufw | reload

- name: ufw | configure default action
  tags: [config]
  ufw: default={{ firewall_default_in }} direction=incoming
  ufw: default={{ firewall_default_out }} direction=outgoing
  notify: ufw | reload

- name: ufw | enable ufw
  tags: [services]
  ufw: state=enabled
