- name: install zramctl
  tags: [zram, system]
  copy: src=zramctl dest=/usr/local/sbin/zramctl mode=755
  notify: restart zram

- name: install zram service
  tags: [zram, system]
  copy: src=zram.service dest=/etc/systemd/system/zram.service
  notify:
    - reload systemd
    - restart zram

- name: enable and start zram
  tags: [zram, system]
  service: name=zram state=started enabled=yes
