- name: install ufw (apt)
  apt: pkg=ufw state=latest
  when: ansible_pkg_mgr == 'apt'

- name: enable ipv6
  lineinfile: >
    dest=/etc/default/ufw
    state=present
    regexp='^IPV6'
    line='IPV6=yes'
  notify: reload firewall

- name: configure rules
  with_dict: firewall
  ufw: >
    {% if item.value.app is defined %}app={{ item.value.app }}{% endif %}
    {% if item.value.src is defined %}src={{ item.value.src }}{% endif %}
    {% if item.value.dest is defined %}dest={{ item.value.dest }}{% endif %}
    {% if item.value.port is defined %}port={{ item.value.port }}{% endif %}
    {% if item.value.proto is defined %}proto={{ item.value.proto }}{% endif %}
    {% if item.value.direction is defined %}direction={{ item.value.direction }}{% endif %}
    {% if item.value.if is defined %}if={{ item.value.if }}{% endif %}
    {% if item.value.log is defined %}log={{ item.value.log }}{% endif %}
    {% if item.value.insert is defined %}insert={{ item.value.insert }}{% endif %}
    {% if item.value.delete is defined %}delete={{ item.value.delete }}{% endif %}
    rule={{ item.value.rule }}
  notify: reload firewall

- name: configure default incoming rule
  ufw: default={{ firewall_default_in}} direction=incoming
  notify: reload firewall

- name: configure default outgoing rule
  ufw: default={{ firewall_default_out}} direction=outgoing
  notify: reload firewall

- name: ufw | enable ufw
  ufw: state=enabled
