- name: create directories
  tags: [tinc, network]
  with_items:
    - /etc/tinc/hosts
  file: path={{ item }} state=directory

- name: configure tinc
  tags: [tinc, network]
  template: src=tinc.conf dest=/etc/tinc/tinc.conf
  notify: restart tinc

- name: transfer tinc scripts
  tags: [tinc, network]
  with_items:
    - tinc-up
    - tinc-down
  template: src={{ item }} dest=/etc/tinc/{{ item }} mode=755
  notify: restart tinc

- name: transfer hosts
  tags: [tinc, network]
  with_items: groups['all']
  template: src=host dest=/etc/tinc/hosts/{{ hostvars[item].network.mesh.name }}
  notify: restart tinc

- name: transfer key
  tags: [tinc, network]
  copy: src={{ keys }}/{{ inventory_hostname }}.priv dest=/etc/tinc/rsa_key.priv mode=600
  notify: restart tinc

- name: install tinc service
  tags: [tinc, network]
  copy: src=tinc.service dest=/etc/systemd/system/tinc.service
  notify:
    - reload systemd
    - restart tinc

- name: enable and start tinc
  tags: [tinc, network]
  service: name=tinc state=started enabled=yes
