#!/bin/sh

### BEGIN INIT INFO
# Provides:          nidd
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: trivial identd implementation
# Description:       trivial identd implementation
### END INIT INFO

. /lib/lsb/init-functions

start() {
  start-stop-daemon -S \
    -x /srv/nidd/nidd \
    -p /var/run/nidd.pid -m  \
    -b \
    -- \
    {{ nidd_ident }}
}

stop() {
  start-stop-daemon -K \
    -x /srv/nidd/nidd \
    -p /var/run/nidd.pid
}

status() {
  if ps ax | grep -v grep | grep '/srv/nidd/nidd' >/dev/null 2>&1; then
    log_success_msg 'nidd running'
  else
    log_failure_msg 'nidd not running'; exit 3
  fi
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; sleep 3; start ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}" ;;
esac
