#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          munin-html
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run Munin's FastCGI server
# Description:       Run Munin's html FastCGI server.
### END INIT INFO#

NAME=munin-html
SOCKET=/run/munin/munin-html.sock
MODE=0660
PID=/run/munin/munin-html.pid
USER=www-data
GROUP=www-data
APP=/usr/lib/munin/cgi/munin-cgi-html

start() {
  spawn-fcgi -s $SOCKET -S -M $MODE -P $PID -u $USER -g $GROUP -f $APP || echo -en "\n already running"
}

stop() {
  killall -QUIT $NAME || echo -en "\n not running"
  rm $SOCKET $PID
}

restart() {
  killall -HUP $NAME || echo -en "\n not running"
  rm $SOCKET $PID
}

case "$1" in
  start)
    echo -n "Starting $NAME: "
    start
  ;;
  stop)
    echo -n "Stopping $NAME: "
    stop
  ;;
  restart|reload)
    echo -n "Restarting $NAME: "
    stop
    sleep 1
    start
  ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
    exit 3
  ;;
esac

exit $?
