- name: reload systemd
  command: systemctl daemon-reload

- name: reload tmpfiles
  command: systemd-tmpfiles --remove --create

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
