- name: configure logstash service
  tags: [logstash, db]
  template: src=logstash.default dest=/etc/default/logstash
  notify: restart logstash

- name: configure logstash grok patterns
  tags: [logstash, logging]
  copy: src=patterns dest=/opt/logstash/patterns/custom
  notify: restart logstash

- name: configure logstash
  tags: [logstash, logging]
  with_items:
    - 10-input-redis-beaver.conf
    - 10-input-redis-stash53.conf
    - 25-parse-auth.conf
    - 25-parse-dns.conf
    - 25-parse-nginx.conf
    - 25-parse-syslog.conf
    - 25-parse-ufw.conf
    - 50-output-statsd-nginx.conf
    - 75-output-elasticsearch.conf
  template: src=conf.d/{{ item }} dest=/etc/logstash/conf.d/{{ item }}
  notify: restart logstash

- name: enable and start logstash
  tags: [logstash, logging]
  service: name=logstash state=started enabled=yes
