hostname = "{{ inventory_hostname }}"
bind-address = "0.0.0.0"
reporting-disabled = true

[logging]
level = "info"
file = "/opt/influxdb/shared/influxdb.log"


[admin]
port = 8083
assets = "/opt/influxdb/current/admin"

[api]
port = 8086
read-timeout = "5s"


[input_plugins]
 [input_plugins.graphite]
 enabled = true
 udp_enabled = true
 port = 2003
 database = "graphite"

[raft]
port = 8090
dir = "/opt/influxdb/shared/data/raft"
#election-timeout = "1s"

[cluster]
#seed-servers = ["host:8090"]

protobuf_port = 8099
protobuf_timeout = "2s"
protobuf_heartbeat = "200ms"
protobuf_min_backoff = "1s"
protobuf_max_backoff = "10s"
write-buffer-size = 1000
max-response-buffer-size = 100
concurrent-shard-query-limit = 10


[storage]
dir = "/opt/influxdb/shared/data/db"
default-engine = "rocksdb"

write-buffer-size = 10000
max-open-shards = 0
point-batch-size = 100
write-batch-size = 5000000
retention-sweep-period = "10m"

[storage.engines.leveldb]
max-open-files = 1000
lru-cache-size = "200m"
[storage.engines.rocksdb]
max-open-files = 1000
lru-cache-size = "200m"
[storage.engines.hyperleveldb]
max-open-files = 1000
lru-cache-size = "200m"
[storage.engines.lmdb]
map-size = "100g"

[wal]
dir = "/opt/influxdb/shared/data/wal"

flush-after = 1000
bookmark-after = 1000
index-after = 1000
requests-per-logfile = 10000
