- name: Common (all)
  hosts: all
  sudo: yes
  roles:
    - { role: common }
    - { role: firewall }
    - { role: log/forwarder, cert: files/log/logstash.crt }
    - { role: utils }
    - { role: firewall/rule, rule: { rule: allow, port: ssh } }
    - { role: firewall/rule, rule: { rule: allow, port: '60000:61000', proto: udp } }
