- name: DNS Servers (dns)
  hosts: dns
  sudo: yes
  roles:
    - role: network/ferm/rule
      name: domain
      rule: |
        @hook pre   "tc class add dev eth0 parent 1:1 classid 1:53 htb rate 5mbps ceil 10mbps";
        @hook pre   "tc qdisc add dev eth0 parent 1:53 handle 53: sfq perturb 10";
        @hook pre   "tc filter add dev eth0 parent 1: proto ip prio 53 handle 53 fw classid 1:53";
        @hook flush "tc filter del dev eth0 prio 53";
        @hook flush "tc qdisc del dev eth0 parent 1:53 handle 53:";
        @hook flush "tc class del dev eth0 parent 1:1 classid 1:53";

        domain (ip ip6) {
          table filter chain INPUT proto (tcp udp) dport domain ACCEPT;
          table mangle chain OUTPUT proto (tcp udp) sport domain MARK set-mark 53;
        }


    - role: dns/unbound
      listen:
        - '{{ network.ipv4.vpn }}'
        - '{{ network.ipv6.vpn }}'
      allow:
        - '{{ network.ipv4.vpn }}/24'
        - '{{ network.ipv6.vpn }}/64'
    - role: dns/nsd
      listen:
        - '{{ network.ipv4.public.0 }}'
        - '{{ network.ipv6.public.0 }}'
        - 127.0.0.1
        - ::1
      transfer:
        # ns1.linode.com
        - 69.93.127.10
        - 2600:3c00::a
        # ns2.linode.com
        - 65.19.178.10
        - 2600:3c01::a
        # ns3.linode.com
        - 75.127.96.10
        - 2600:3c02::a
        # ns4.linode.com
        - 207.192.70.10
        - 2600:3c03::a
        # ns5.linode.com
        - 109.74.194.10
        - 2a01:7e00::a
        # slave.dns.he.net
        - 216.218.133.2
        - 2001:470:600::2
      notify:
        # ns1.linode.com
        - 69.93.127.10
        - 2600:3c00::a
        # ns2.linode.com
        - 65.19.178.10
        - 2600:3c01::a
        # ns3.linode.com
        - 75.127.96.10
        - 2600:3c02::a
        # ns4.linode.com
        - 207.192.70.10
        - 2600:3c03::a
        # ns5.linode.com
        - 109.74.194.10
        - 2a01:7e00::a
        # ns1.he.net
        - 216.218.130.2
        - 2001:470:100::2

    - role: dns/nsd/zone
      zone: neer.io
      zonefile: files/dns/neer.io.zone.signed
    - role: dns/nsd/zone
      zone: neergaard.me
      zonefile: files/dns/neergaard.me.zone.signed
    - role: dns/nsd/zone
      zone: neersighted.com
      zonefile: files/dns/neersighted.com.zone.signed
    - role: dns/nsd/zone
      zone: royalspades.co
      zonefile: files/dns/royalspades.co.zone
    - role: dns/nsd/zone
      zone: saynay.me
      zonefile: files/dns/saynay.me.zone.signed
    - role: dns/nsd/zone
      zone: singulo.co
      zonefile: files/dns/singulo.co.zone

    - role: logging/stash53
      redis:
        host: nitrogen.neersighted.com.int
