- name: DNS Servers (dns)
  hosts: dns
  sudo: yes
  roles:
    - { role: dns/server }
    - { role: firewall/rule, rule: { rule: allow, port: domain } }

    - { role: dns/zone, zone: neer.io, zonefile: files/dns/neer.io.zone.signed }
    - { role: dns/zone, zone: neergaard.me, zonefile: files/dns/neergaard.me.zone.signed }
    - { role: dns/zone, zone: neersighted.com, zonefile: files/dns/neersighted.com.zone.signed }
    - { role: dns/zone, zone: royalspades.co, zonefile: files/dns/royalspades.co.zone }
    - { role: dns/zone, zone: saynay.me, zonefile: files/dns/saynay.me.zone.signed }
    - { role: dns/zone, zone: singulo.co, zonefile: files/dns/singulo.co.zone }

    - { role: log/stash53, server: '{{ hostvars['nitrogen.neersighted.com'].network.ipv4.private }}/6379' }
