- name: Log Servers (log)
  hosts: log
  sudo: yes
  roles:
    - { role: log/server, cert: files/log/logstash.crt, key: files/log/logstash.key }
    - { role: firewall/rule, rule: { rule: allow, port: 5000, proto: tcp } }
