- name: Mail Servers (mail)
  hosts: mail
  sudo: yes
  roles:
    - role: network/ferm/rule
      name: smtp
      rule: |
        domain (ip ip6) {
          table filter chain INPUT proto (tcp udp) dport smtp ACCEPT;
          table mangle chain OUTPUT proto (tcp udp) sport smtp MARK set-mark 23;
        }


    - role: security/ssl/certificate
      cert: files/ssl/hydrogen.neersighted.com.pem
      when: inventory_hostname == 'hydrogen.neersighted.com'

    - role: mail/postfix
      to: bjorn@neersighted.com
      auth:
        user: bjorn@neersighted.com
        pass: 9K2k6758tey9HD56
      domains:
        - neer.io
        - neergaard.me
        - neersighted.com
        - royalspades.co
        - saynay.me
        - singulo.co
      relay:
        host: mail.messagingengine.com
      ssl:
        cert: /etc/ssl/hydrogen.neersighted.com.pem
        key: /etc/ssl/hydrogen.neersighted.com.pem
      when: inventory_hostname == 'hydrogen.neersighted.com'
