- name: Web Servers (web)
  hosts: web
  sudo: yes
  roles:
    - { role: web/nginx }
    - { role: firewall/rule, rule: { rule: allow, port: http } }
    - { role: firewall/rule, rule: { rule: allow, port: https } }

    - { role: web/nginx/site, site: localhost, conf: files/web/localhost.conf }

    - { role: web/elastichq }
    - { role: web/nginx/site, site: elastichq.neersighted.com, conf: files/web/elastichq.neersighted.com.conf }
    - { role: web/kibana }
    - { role: web/nginx/site, site: kibana.neersighted.com, conf: files/web/kibana.neersighted.com.conf }
    - { role: web/kopf }
    - { role: web/nginx/site, site: kopf.neersighted.com, conf: files/web/kopf.neersighted.com.conf }

    - { role: web/nginx/site, site: neer.io, conf: files/web/neer.io.conf }
    - { role: web/nginx/site, site: neergaard.me, conf: files/web/neergaard.me.conf }
    - { role: web/nginx/site, site: neersighted.com, conf: files/web/neersighted.com.conf }
    - { role: web/nginx/site, site: gapps.itvends.com, conf: files/web/gapps.itvends.com.conf }
