- name: Web Servers (web)
  hosts: web
  sudo: yes
  roles:
    - role: network/ferm/rule
      name: http
      rule: |
        domain (ip ip6) {
          table filter chain INPUT proto tcp dport (http https) ACCEPT;
          table mangle chain OUTPUT proto tcp sport (http https) MARK set-mark 80;
        }
    - role: network/tc/mark
      mark: 80
      rate: 5mbps
      ceil: 15mbps


    - role: security/ssl/certificate
      cert: files/ssl/dhparam.pem
    - role: security/ssl/certificate
      cert: files/ssl/gandi-ca.pem
    - role: security/ssl/certificate
      cert: files/ssl/neer.io.pem
    - role: security/ssl/certificate
      cert: files/ssl/neergaard.me.pem
    - role: security/ssl/certificate
      cert: files/ssl/neersighted.com.pem

    - role: web/nginx
    - role: web/uwsgi

    - role: web/nginx/site
      name: localhost
      conf: files/web/localhost.conf

    - role: web/elastichq
    - role: web/nginx/site
      name: elastichq.neersighted.com
      conf: files/web/elastichq.neersighted.com.conf

    - role: web/grafana
    - role: web/nginx/site
      name: grafana.neersighted.com
      conf: files/web/grafana.neersighted.com.conf

    - role: web/kibana
    - role: web/nginx/site
      name: kibana.neersighted.com
      conf: files/web/kibana.neersighted.com.conf

    - role: web/kopf
    - role: web/nginx/site
      name: kopf.neersighted.com
      conf: files/web/kopf.neersighted.com.conf

    - role: web/nginx/site
      name: neer.io
      conf: files/web/neer.io.conf
    - role: web/nginx/site
      name: neergaard.me
      conf: files/web/neergaard.me.conf
    - role: web/nginx/site
      name: neersighted.com
      conf: files/web/neersighted.com.conf
    - role: web/nginx/site
      name: gapps.itvends.com
      conf: files/web/gapps.itvends.com.conf
