- name: Web Servers (web)
  hosts: web
  sudo: yes
  roles:
    - role: network/ferm/rule
      name: http
      rule: |
        @hook pre   "tc class add dev eth0 parent 1:1 classid 1:80 htb rate 5mbps ceil 15mbps";
        @hook pre   "tc qdisc add dev eth0 parent 1:80 handle 80: sfq perturb 10";
        @hook pre   "tc filter add dev eth0 parent 1: prio 80 handle 80 fw classid 1:80";
        @hook flush "tc filter del dev eth0 parent 1: prio 80";
        @hook flush "tc qdisc del dev eth0 parent 1:80 handle 80:";
        @hook flush "tc class del dev eth0 parent 1:1 classid 1:80";

        domain (ip ip6) {
          table filter chain INPUT proto tcp dport (http https) ACCEPT;
          table mangle chain OUTPUT proto tcp sport (http https) MARK set-mark 80;
        }


    - role: security/ssl/certificate
      cert: files/ssl/dhparam.pem
    - role: security/ssl/certificate
      cert: files/ssl/gandi-ca.pem
    - role: security/ssl/certificate
      cert: files/ssl/neer.io.pem
    - role: security/ssl/certificate
      cert: files/ssl/neergaard.me.pem
    - role: security/ssl/certificate
      cert: files/ssl/neersighted.com.pem

    - role: web/nginx
    - role: web/uwsgi

    - role: web/nginx/site
      name: localhost
      conf: files/web/localhost.conf

    - role: web/elastichq
    - role: web/nginx/site
      name: elastichq.neersighted.com
      conf: files/web/elastichq.neersighted.com.conf

    - role: web/grafana
    - role: web/nginx/site
      name: grafana.neersighted.com
      conf: files/web/grafana.neersighted.com.conf

    - role: web/kibana
    - role: web/nginx/site
      name: kibana.neersighted.com
      conf: files/web/kibana.neersighted.com.conf

    - role: web/kopf
    - role: web/nginx/site
      name: kopf.neersighted.com
      conf: files/web/kopf.neersighted.com.conf

    - role: web/nginx/site
      name: neer.io
      conf: files/web/neer.io.conf
    - role: web/nginx/site
      name: neergaard.me
      conf: files/web/neergaard.me.conf
    - role: web/nginx/site
      name: neersighted.com
      conf: files/web/neersighted.com.conf
    - role: web/nginx/site
      name: gapps.itvends.com
      conf: files/web/gapps.itvends.com.conf
