- name: Web Servers (web)
  hosts: web
  sudo: yes
  roles:
    - { role: web/server }
    - { role: firewall/rule, rule: { rule: allow, port: http } }
    - { role: firewall/rule, rule: { rule: allow, port: https } }

    - { role: web/site, site: localhost, conf: files/web/localhost.conf }

    - { role: web/kibana }
    - { role: web/site, site: kibana.neersighted.com, conf: files/web/kibana.neersighted.com.conf }

    - { role: web/elasticsearch-hq }
    - { role: web/site, site: elasticsearch-hq.neersighted.com, conf: files/web/elasticsearch-hq.neersighted.com.conf }

    - { role: web/site, site: neer.io, conf: files/web/neer.io.conf }
    - { role: web/site, site: neergaard.me, conf: files/web/neergaard.me.conf }
    - { role: web/site, site: neersighted.com, conf: files/web/neersighted.com.conf }
    - { role: web/site, site: gapps.itvends.com, conf: files/web/gapps.itvends.com.conf }
