- name: extract kibana
  tags: [kibana, web]
  unarchive: src=kibana.tgz dest=/srv/web creates=/srv/web/kibana/config.js

- name: configure kibana
  tags: [kibana, web]
  template: src=config.js dest=/srv/web/kibana/config.js
