- name: reload systemd
  command: systemctl daemon-reload

- name: reload kernel modules
  service: name=systemd-modules-load state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload ferm
  service: name=ferm state=restarted
