- name: nidd | fetch nidd sources
  git: repo=git://github.com/neersighted/nidd dest=/srv/nidd
  register: git

- name: nidd | build and install nidd
  when: git.changed
  shell: cd /srv/nidd && go build
  notify: restart nidd

- name: nidd | install nidd service
  template: src=nidd dest=/etc/init.d/nidd mode=755

- name: nidd | enable and start nidd
  service: name=nidd state=started enabled=yes
