- name: transfer zone {{ zone }}
  tags: [zone, nsd, dns]
  copy: src={{ zonefile }} dest=/srv/dns/{{ zonefile|basename }}
  notify: reload nsd

- name: configure zone {{ zone }}
  tags: [zone, nsd, dns]
  template: src=zone.conf dest=/etc/nsd/nsd.conf.d/{{ zone }}.conf
  notify:
    - assemble nsd.conf.d
    - restart nsd
