- name: ssh | disable password authentication
  tags: [ssh, security, common]
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp='^#?PasswordAuthentication'
    line='PasswordAuthentication no'
    state=present
  notify: restart ssh
