- name: java | add java repo key (apt)
  apt_key: id=EEA14886 keyserver=keyserver.ubuntu.com state=present
  when: ansible_pkg_mgr == 'apt'

- name: java | add java repo (apt)
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu utopic main' state=present
  register: java_repo
  when: ansible_pkg_mgr == 'apt'

- name: java | accept java license (apt)
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: ansible_pkg_mgr == 'apt' and java_repo.changed

- name: java | install java (apt)
  apt: pkg=oracle-java8-installer state=latest
  when: ansible_pkg_mgr == 'apt'
