dependencies:
  - role: file/directory
    path: /etc/nginx/nginx.conf.d

  - role: packages/apt/add_key
    args:
      id: 7BD9BF62
      url: 'http://nginx.org/keys/nginx_signing.key'
  - role: packages/apt/add_repo
    args:
      repo: 'deb http://nginx.org/packages/mainline/debian wheezy nginx'

  - role: packages/apt
    args:
      pkg: nginx
