- name: accounts | configure ansible group
  tags: [ansible]
  group: >
    name=ansible
    gid=500
    system=yes

- name: accounts | configure ansible user
  tags: [ansible]
  user: >
    name=ansible
    uid=5000
    group=ansible
    home=/ansible
    system=yes

- name: accounts | configure ansible authorized_key
  tags: [ansible, ssh]
  authorized_key: >
    user=ansible
    key='{{ lookup('file', 'deploy_key.pub') }}'

- name: accounts | configure groups
  tags: []
  group: >
    name={{ item.key }}
    {% if item.value.gid is defined %}gid={{ item.value.gid }}{% endif %}
    {% if item.value.system is defined %}system={{ item.value.system }}{% endif %}
    state={{ item.value.state }}
  with_dict: accounts_groups

- name: accounts | configure users
  tags: []
  user: >
    name={{ item.key }}
    {% if item.value.uid is defined %}uid={{ item.value.uid }}{% endif %}
    {% if item.value.group is defined %}group={{ item.value.group }}{% endif %}
    {% if item.value.groups is defined %}groups={{','.join(item.value.groups)}}{% endif %}
    {% if item.value.append is defined %}append={{ item.value.append }}{% endif %}
    {% if item.value.home is defined %}home={{ item.value.home }}{% endif %}
    {% if item.value.createhome is defined %}home={{ item.value.createhome }}{% endif %}
    {% if item.value.pass is defined %}password={{ item.value.pass }}{% endif %}
    {% if item.value.shell is defined %}shell={{ item.value.shell }}{% endif %}
    {% if item.value.comment is defined %}comment={{ item.value.comment }}{% endif %}
    {% if item.value.system is defined %}system={{ item.value.system }}{% endif %}
    state={{ item.value.state }}
  with_dict: accounts_users

- name: accounts | configure authorized_keys
  tags: [ssh,security]
  authorized_key: user={{ item.key }} key='{{ item.value.authorized_key }}'
  with_dict: accounts_users
