- name: accounts | grant ansible sudo
  tags: [sudo, config]
  lineinfile: >
    dest=/etc/sudoers
    state=present
    insertafter='^root'
    line='ansible ALL=(ALL) NOPASSWD: ALL'
    validate='visudo -cf %s'

- name: security | grant %wheel sudo
  tags: [sudo, config]
  lineinfile: >
    dest=/etc/sudoers
    state=present
    insertafter='\# Allow'
    line='%wheel  ALL=(ALL:ALL) ALL'
    validate='visudo -cf %s'

- name: security | disable %sudo sudo
  tags: [sudo, config]
  lineinfile: >
    dest=/etc/sudoers
    state=absent
    regexp='^%sudo'

- name: security | disable password-authenticated ssh
  tags: [ssh, config]
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?PasswordAuthentication'
    line='PasswordAuthentication no'
  notify: security | restart sshd
