- name: Log Servers (log)
  hosts: log
  sudo: yes
  roles:
  - role: database/redis
    appendonly: 'no'
  - role: database/elasticsearch
    cluster: log

  - role: logging/logstash
    timezone: America/Los_Angeles
    elasticsearch:
      cluster: log
    statsd:
      host: nitrogen.neersighted.com.int
