- name: install statsite
  tags: [statsite, metrics]
  copy: src=statsite dest=/usr/local/bin/statsite mode=755
  notify: restart statsite

- name: install statsite sinks
  tags: [statsite, metrics]
  with_items:
    - graphite
    - influxdb
  copy: src={{ item }}.py dest=/usr/local/bin/statsite.{{ item }} mode=755
  notify: restart statsite

- name: configure statsite
  tags: [statsite, metrics]
  template: src=statsite.conf dest=/etc/statsite/statsite.conf
  notify: restart statsite

- name: configure statsite influx sink
  tags: [statsite, metrics]
  template: src=influxdb.conf dest=/etc/statsite/influxdb.conf
  notify: restart statsite

- name: install statsite service
  tags: [statsite, metrics]
  copy: src=statsite.service dest=/etc/systemd/system/statsite.service
  notify:
    - reload systemd
    - restart statsite

- name: enable and start statsite
  tags: [statsite, metrics]
  service: name=statsite state=started enabled=yes
