- name: nginx| add nginx repo key (apt)
  apt_key: id=7BD9BF62 url=http://nginx.org/keys/nginx_signing.key state=present
  when: ansible_pkg_mgr == 'apt'

- name: nginx | add nginx repo (apt)
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ wheezy nginx' state=present
  when: ansible_pkg_mgr == 'apt'

- name: nginx | install nginx (apt)
  apt: pkg=nginx state=latest
  when: ansible_pkg_mgr == 'apt'

- name: nginx | configure nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf validate='nginx -tc /etc/nginx/nginx.conf'
  notify: restart nginx

- name: nginx | configure vhosts
  with_dict: vhosts
  template: src=vhost.conf dest=/etc/nginx/conf.d/{{ item.key }}.conf
  notify: reload nginx

- name: nginx | copy ssl bundles
  copy: src=files/web/ssl/ dest=/etc/nginx/ssl/ owner=nginx
  notify: reload nginx

- name: nginx | enable and start nginx
  service: name=nginx state=started enabled=yes
