- name: nginx | configure nginx.conf.d
  file: path=/etc/nginx/nginx.conf.d state=directory

- name: nginx | configure nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf validate='nginx -tc %s'
  notify: restart nginx

- name: nginx | enable and start nginx
  service: name=nginx state=started enabled=yes
