#!/usr/bin/env bash

#
# genhost - generate unused hostnames by randomly picking from a word list
#

readonly wordlist='wordlist'
readonly domain='neersighted.com'

rand() {
  local max=$((32768 / $1 * $1))
  while (( (r=$RANDOM) >= max )); do :; done
  r=$(( r % $1 ))
}

if [[ -z $1 ]]; then
  echo 'Usage: genhost <integer>'
  echo 'Generate unused hostnames by randomly picking from a word list'
  exit 1
else
  if [[ $1 == *[!0-9]* ]]; then
    echo "'$1' is not a positive integer"
    exit 1
  fi
fi

unset lines n
while IFS= read -r 'lines[n++]'; do :; done < <(sed '/^#/d' "$wordlist")

for i in $(seq $1); do
  rand $n
  echo "${lines[r]}.${domain}"

  case $OSTYPE in
    darwin*)
      /usr/bin/sed -i '' "s/${lines[r]}/#${lines[r]}/g" "$wordlist"
      ;;
    linux*)
      /usr/bin/sed -i "s/${lines[r]}/#${lines[r]}/g" "$wordlist"
      ;;
  esac
done

exit 0
